/*
 * config.h
 *
 *  Created on: Feb 24, 2023
 *      Author: marek
 */

#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

#define CONFIG_MPU_ENABLE								0
#define CONFIG_RESET_REASON_ALWAYS_POWER_ON_RESET 		0
#define CONFIG_WATCHDOG_ENABLE 							0

#define CONFIG_TRACE_ENABLE								1

#define CONFIG_APPS_DIGITAL_IN_ENABLE					1
#define CONFIG_APPS_DIGITAL_OUT_ENABLE					1

#define CONFIG_SLAVE_REGS_BY_SPI_T200_SPI_SLAVE			1


#define CONFIG_SLAVE_REGS_SPI_T200_SPI_SLAVE			CONFIG_SLAVE_REGS_BY_SPI_T200_SPI_SLAVE

#define CONFIG_SPI_SLAVE_CS_IRQ  						1

#define CONFIG_SPI_SLAVE_REGS_GENERATE_IRQ				1




/* Test pins */
#define CONFIG_TEST_PINS_MAIN							0
#define CONFIG_TEST_PINS_SPI_SLAVE						0
#define CONFIG_TEST_PINS_SPI_SLAVE_SS_IRQ				0

/* SPI Slave */

#define CONFIG_SPI_SLAVE_WORD32_DATA_BUFFER_LENGTH		256

#endif /* INC_CONFIG_H_ */
