/*
 * types.h
 *
 *  Created on: Feb 24, 2023
 *      Author: marek
 */

#ifndef INC_TYPES_H_
#define INC_TYPES_H_

#include <stdint.h>

#define TRUE 1
#define FALSE 0

typedef uint8_t BOOL;

typedef enum {
	BTS_RC_OK = 0,
	BTS_RC_ERR_INV_ARG = -1,
	BTS_RC_ERR_INV_CRC = -2,
	BTS_RC_ERR_INV_ADDRESS = -3,
	BTS_RC_ERR_INV_DATA = -4,
	BTS_RC_ERR_INV_VERSION = -5,
	BTS_RC_ERR_INV_STATE = -6,
	BTS_RC_ERR_INV_WRITE_PROTECT = -7,
	BTS_RC_ERR_SEQNC_ERR = -8,
	BTS_RC_ERR_NOT_FOUND = -9,

	BTS_RC_ERR_NO_MEMORY = -10,
	BTS_RC_ERR_NO_IMPLEMENTATION = -11,
	BTS_RC_ERR_TIMEOUT = -12,
	BTS_RC_ERR_NOT_ACK = -13,
	BTS_RC_NOT_READY = -14,
	BTS_RC_ERR_NOT_SUPPORTED = -15,

	BTS_RC_SPI_IO_ERR = -200,

	BTS_RC_HAL_FLASH_IO_ERR = -201,
	BTS_RC_HAL_FLASH_NOT_FOUND = -202,

	BTS_RC_FLASH_ERROR = -300,
	BTS_RC_FLASH_PAGE_NOT_FOUND = -301,
	BTS_RC_FLASH_BUFFER_ERROR = -302,

	BTS_RC_FPGA_ERROR = -400,
	BTS_RC_FPGA_LOAD_CONFIG_ERROR = -401,


	BTS_RC_GPIO_INV_PORT = -500,
	BTS_RC_GPIO_INV_PIN = -501,
	BTS_RC_GPIO_INV_AF = -502,

	BTS_RC_I2C_INV_CTRL = -600,


	BTS_RC_DPLL_NOT_READY = -1000,

	BTS_RC_GPS_UBX_INVALID_COMM_INTERFACE_ID = -2000,
	BTS_RC_GPS_UBX_MSG_ID_MISMATCH			 = -2001,

	BTS_RC_GPS_UBX_PACKET_INV_LENGTH = -3000,
	BTS_RC_GPS_UBX_PACKET_INV_HEADER = -3001,
	BTS_RC_GPS_UBX_PACKET_INV_CHKSUM = -3002,

	BTS_RC_LAST
} bts_rc;

#endif /* INC_TYPES_H_ */
